import './styles/global.css';
import type {Metadata} from "next";
import Providers from "@/app/components/providers/Providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={"dark"}>
    <body>
    <Providers>
      {children}
    </Providers>
    </body>
    </html>
  );
}
